### ISSUE TITLE
env_check fails if Simplicity Commander is not present when following ReadMe

### ISSUE THREAD

**Issue by pollockm** [aws-samples/aws-iot-core-for-amazon-sidewalk-sample-app#43]
Readme suggests running the env_check script before filling in the configuration file.  Thus, if using a hardware platform other than Silicon Labs, user will get a failure message complaining about not being able to find Simplicity Commander:

`[ERROR]  	FAIL! Unable to find Simplicity Commander! Please install https://community.silabs.com/s/article/simplicity-commander and add the path to config.yaml`

Ask: change the order of steps in the ReadMe file to first fill out the config (and select a hardware platform), then run the env_check script to avoid confusion.

**Comment by Krzpaw** [comment]
Hello @pollockm, thank you for your comment, this is a good point.
I've created a pull request, which moves env_check.py hint at the end of the _Fill out configuration file_ section.
